server:
  applicationConnectors:
    - type: http
      port: 4000

  adminConnectors:
    - type: http
      port: 4001

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: admin

  # the password
  password: voC7oj2D

  # the JDBC URL
  url: jdbc:mysql://hackathon.cudqte3kvjgc.us-east-1.rds.amazonaws.com:3306/hackathon

  # any properties specific to your JDBC driver:
#  properties:
#    charSet: UTF-8
#    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false